# Generated by Django 5.1.2 on 2024-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
