# Generated by Django 5.1.2 on 2024-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_quantity_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
