# Generated by Django 5.1.1 on 2024-11-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='checked_out',
        ),
    ]
