# Generated by Django 5.1.1 on 2024-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_user_type_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
