# Generated by Django 5.1.2 on 2024-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
