# Generated by Django 5.1.2 on 2024-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
