# Generated by Django 5.1.2 on 2024-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
