# Generated by Django 5.1.2 on 2024-10-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_time',
        ),
    ]
