# Generated by Django 5.1.2 on 2024-10-31 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerUsername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
