# Generated by Django 5.1.2 on 2024-10-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_sellerusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerUsername',
            new_name='seller_username',
        ),
    ]
