# Generated by Django 5.1.2 on 2024-10-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_sellerusername_product_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_username',
        ),
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(limit_choices_to={'user_type': 'seller'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
