# Generated by Django 5.1.2 on 2024-10-31 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_seller_username_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
