# Generated by Django 5.1.2 on 2024-10-31 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(limit_choices_to={'user_type': 'seller'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
