# Generated by Django 5.1.2 on 2024-10-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_sellerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerID',
            new_name='seller_username',
        ),
    ]
