# Generated by Django 5.1.2 on 2024-10-31 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_sellerid_product_seller_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_username',
            field=models.ForeignKey(limit_choices_to={'user_type': 'seller'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
