# Generated by Django 5.1.2 on 2024-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_cart_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_products',
            field=models.JSONField(null=True),
        ),
    ]
